change text
Pleum1231/PreeChampAssignment1 pull request #1
Opened 2021-04-08 11:38 UTC by Pleum1231

Test Pull Request

2021-04-08 15:43 UTC, Chameza25964 approved these changes

2021-04-08 17:12 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
> +class LoadingDialog (var activity: MainActivity){
เปลี่ยนไปใช้ Context แทน MainActivity

2021-04-08 17:13 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
> +        var builder = AlertDialog.Builder(activity)
เปลี่ยน var เป็น val

2021-04-08 17:13 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
> +        var inflater : LayoutInflater = activity.layoutInflater
เปลี่ยน var เป็น val

2021-04-08 17:15 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
> +        textViewNumber.setText("$numText")
textViewNumber.text = "$numText"

2021-04-08 17:15 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
>          var numText :String = data!!.getIntExtra("number",0).toString()
เปลี่ยน var เป็น val

2021-04-08 17:16 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
>          var numText :String = data!!.getIntExtra("number",0).toString()
- เปลี่ยน var เป็น val
- numText? คืออะไร

2021-04-08 17:17 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
>          var numText :String = data!!.getIntExtra("number",0).toString()
แล้วถ้า data ที่เป็น Intent มันมาเป็น null อ่ะ แอปจะ crash ไหม ลองเช็คด้วยการไม่ส่งตัวเลขกลับมา

2021-04-08 17:19 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
> +class LoadingDialog (var activity: MainActivity){
เปลี่ยน var เป็น val

2021-04-08 17:20 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
>          builder.setView(inflater.inflate(R.layout.loading_dialog,null))
ตรงนี้ลองใช้ getLayoutInflater().inflate ดูว่ามันได้ไหม ถ้าไม่ได้ก็ให้ก็ใช้เหมือนเดิม

2021-04-08 17:20 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
>          dialog  = builder.create()
space เกิน

2021-04-08 17:21 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
> +class LoadingDialog (var activity: MainActivity){
ใส่ space ระหว่าง 2 อันนี้ ){

2021-04-08 17:21 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
>      fun startLoadingDialog(){
ใส่ space ระหว่าง 2 อันนี้ ){

2021-04-08 17:22 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
>      fun dismissDialog(){
ใส่ space ระหว่าง 2 อันนี้ ){

2021-04-08 17:22 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
>              var loadingDialog = LoadingDialog(this@MainActivity)
เปลี่ยน var เป็น val

2021-04-08 17:23 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
> +            var intent = Intent(this@MainActivity, MainActivity2::class.java)
เปลี่ยน var เป็น val

2021-04-08 17:23 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
> +                loadingDialog.dismissDialog() },2000)
new line ตัว } ลงมาให้มันตรงกับ handler

2021-04-08 17:24 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity2.kt
> +            var sendData= Intent()
เปลี่ยน var เป็น val

2021-04-08 17:24 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity2.kt
> +            var sendData= Intent()
sendData คืออะไร ?

2021-04-08 17:25 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity2.kt
> +            var randNum = Random.nextInt(1, 10)
เปลี่ยน var เป็น val

2021-04-08 17:25 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity2.kt
> +            var randNum = Random.nextInt(1, 10)
randNum คืออะไร ?

2021-04-08 17:25 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity2.kt
> +            var sendData= Intent()
ใส่ space รอบๆ operator ทุกครั้งด้วย

2021-04-08 17:26 UTC, Chameza25964 commented on app/src/main/res/layout/activity_main.xml
>          app:layout_constraintRight_toRightOf="parent"
เปลี่ยนไปใช้ End_ToEndOf

2021-04-08 17:27 UTC, Chameza25964 commented on app/src/main/res/layout/activity_main.xml
>          app:layout_constraintLeft_toLeftOf="parent"
เปลี่ยนไปใช้ Start_toStartOf

2021-04-08 17:29 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
>      private var dialog: AlertDialog? = null
เว้นระหว่างท่อน Variables Declaration กับ function ด้วย เวลาอ่านจะได้ดูออกว่าส่วนไหนเป็นส่วนไหน

2021-04-08 18:11 UTC, Pleum1231 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
>          var numText :String = data!!.getIntExtra("number",0).toString()
Cash ครับ

2021-04-09 09:19 UTC, Pleum1231 commented on app/src/main/java/com/example/pchampassignment1/LoadingDialog.kt
>          builder.setView(inflater.inflate(R.layout.loading_dialog,null))
ไม่ได้ครับ

2021-04-09 15:01 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
> +        textViewNumber.text="$numberFromMainActivity2"
อย่าลืมใส่ space ระหว่าง operator

2021-04-09 15:04 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
> +        val numberFromMainActivity2 :String = data?.getIntExtra("number",0).toString()
data?.let { data ->
    val numberFromMainActivity2: String = data.getIntExtra("number", 0).toString()
}

2021-04-09 15:05 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
>              },2000)
}, 2000)

2021-04-09 15:05 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity.kt
> +                startActivityForResult(intent,1)
intent, 1)

2021-04-09 15:06 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity2.kt
> +        buttonBackPage.setOnClickListener{
setOnClickListener {

2021-04-09 15:06 UTC, Chameza25964 commented on app/src/main/java/com/example/pchampassignment1/MainActivity2.kt
> +            setResult(Activity.RESULT_OK,intent)
, intent)

2021-04-09 16:02 UTC, Chameza25964 requested changes
Pass reviewed.

2021-04-09 16:10 UTC, merged